// packages/@eviljs/solid/html.tsx
import type {JSX} from 'solid-js'
import {Show, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {classes} from './classes.js'

export function Html(props: HtmlProps): JSX.Element {
    const [_, otherProps] = splitProps(props, ['tag'])

    return (
        <Show when={props.children}>
            <Dynamic
                {...otherProps}
                component={props.tag ?? 'div'}
                class={classes('Html-2c6a', props.class)}
                innerHTML={String(props.children ?? '')}
            />
        </Show>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface HtmlProps extends JSX.HTMLAttributes<HTMLElement> {
    tag?: undefined | keyof JSX.IntrinsicElements
    children: undefined | number | string
}

// packages/@eviljs/react/html.tsx
import {forwardRef} from 'react'
import {Box, type BoxProps} from './box.js'
import {classes} from './classes.js'

export const Html = forwardRef(function Html<T extends Element = HTMLElement>(
    props: HtmlProps,
    ref: React.ForwardedRef<T>
) {
    const {children, className, ...otherProps} = props

    return (
        <Box
            {...otherProps}
            ref={ref as React.ForwardedRef<HTMLElement>}
            className={classes('Html-b218', className)}
            dangerouslySetInnerHTML={{__html: children ?? ''}}
        />
    )
}) as (
    & (<T extends Element = HTMLElement>(props: HtmlProps<T>) => JSX.Element)
    & Pick<React.FunctionComponent, 'displayName'>
)
Html.displayName = 'Html'

// Types ///////////////////////////////////////////////////////////////////////

export interface HtmlProps<T extends Element = HTMLElement> extends BoxProps<T> {
    children?: undefined | string
}
