// packages/@eviljs/solid/message.tsx
import type {I18nMessageArgs} from '@eviljs/std/i18n.js'
import {isString} from '@eviljs/std/type-is.js'
import type {Accessor, JSX} from 'solid-js'
import {Show, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {classes} from './classes.js'
import {createI18nMessage} from './i18n.js'

export function Message(props: MessageProps) {
    const [_, otherProps] = splitProps(props, ['args', 'children', 'tag'])

    const message = createI18nMessage(
        () => isString(props.children)
            ? props.children
            : undefined
        ,
        props.args,
    )

    return (
        <Show when={message()}>
            <Dynamic
                {...otherProps}
                component={props.tag ?? 'span'}
                class={classes('Text-6e34', props.class)}
                data-key={message() !== props.children
                    ? props.children
                    : undefined
                }
                children={message()}
            />
        </Show>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface MessageProps extends JSX.HTMLAttributes<HTMLElement> {
    args?: undefined | I18nMessageArgs | Accessor<I18nMessageArgs>
    children: undefined | string
    tag?: undefined | keyof JSX.IntrinsicElements
}

// packages/@eviljs/react/message.tsx
import {createElement, memo} from 'react'
import type {BoxProps} from './box.js'
import {classes} from './classes.js'
import {useI18nMessage, type I18nMessageArgs, type I18nMessageKey} from './i18n.js'
import type {VoidProps} from './type.js'

export const Message = memo(function Message(props: MessageProps) {
    const {children, className, args, tag, ...otherProps} = props
    const message = useI18nMessage(children, args)

    return (
        createElement(tag ?? 'span', {
            ...otherProps,
            className: classes('Message-cea2', className),
            'data-key': message !== children ? children : undefined,
        }, message)
    )
})

export function Translate(props: TranslateProps) {
    const {children, args} = props
    const message = useI18nMessage(children, args)

    return message
}

// Types ///////////////////////////////////////////////////////////////////////

export interface MessageProps extends VoidProps<BoxProps>, TranslateProps {
}

export interface TranslateProps {
    args?: undefined | I18nMessageArgs
    children: I18nMessageKey
}
