// packages/@eviljs/solid/text.tsx
import type {MsgValues} from '@eviljs/std/i18n.js'
import {isString} from '@eviljs/std/type.js'
import type {Accessor, JSX} from 'solid-js'
import {Show, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {classes} from './classes.js'
import {createI18nMessage} from './i18n.js'

export function Text(props: TextProps) {
    const [_, otherProps] = splitProps(props, ['args', 'children', 'tag'])

    const message = createI18nMessage(
        () => isString(props.children)
            ? props.children
            : undefined
        ,
        props.args,
    )

    return (
        <Show when={message()}>
            <Dynamic
                {...otherProps}
                component={props.tag ?? 'span'}
                class={classes('Text-6e34', props.class)}
                data-key={message() !== props.children
                    ? props.children
                    : undefined
                }
                children={message}
            />
        </Show>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface TextProps extends JSX.HTMLAttributes<HTMLElement> {
    args?: undefined | MsgValues | Accessor<MsgValues>
    children: undefined | string
    tag?: undefined | keyof JSX.IntrinsicElements
}

// packages/@eviljs/react/text.tsx
import {isString} from '@eviljs/std/type.js'
import {createElement, memo, useMemo} from 'react'
import type {BoxProps} from './box.js'
import {classes} from './classes.js'
import type {MsgValues} from './i18n.js'
import {useI18n} from './i18n.js'

export const Text = memo(function Text(props: TextProps) {
    const {children, className, args, tag, ...otherProps} = props
    const {translate} = useI18n()!

    const message = useMemo(() => {
        if (! isString(children)) {
            return
        }
        return translate(children, args)
    }, [children, args])

    if (! children || ! message) {
        return <>{children}</>
    }

    return (
        createElement(tag ?? 'span', {
            ...otherProps,
            className: classes('Text-cea2', className),
            'data-key': message !== children ? children : undefined,
        }, message)
    )
})

// Types ///////////////////////////////////////////////////////////////////////

export interface TextProps extends BoxProps {
    args?: undefined | MsgValues
    children?: undefined | string
}
