// packages/@eviljs/react/ts/html.tsx
import {Box, type BoxProps} from './box.js'
import {classes} from './classes.js'
import type {Props} from './props.js'

export function Html(props: Props<HtmlProps>): React.JSX.Element {
    const {children, className, ...otherProps} = props

    return (
        <Box
            {...otherProps}
            className={classes('Html-b218', className)}
            dangerouslySetInnerHTML={{__html: children ?? ''}}
        />
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface HtmlProps<T extends Element = HTMLElement> extends BoxProps<T> {
    children?: undefined | string
}

// packages/@eviljs/solid/html.tsx
import type {JSX} from 'solid-js'
import {Show, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {classes} from './classes.js'

export function Html(props: HtmlProps): JSX.Element {
    const [_, otherProps] = splitProps(props, ['tag'])

    return (
        <Show when={props.children}>
            <Dynamic
                {...otherProps}
                component={props.tag ?? 'div'}
                class={classes('Html-2c6a', props.class)}
                innerHTML={String(props.children ?? '')}
            />
        </Show>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface HtmlProps extends JSX.HTMLAttributes<HTMLElement> {
    tag?: undefined | keyof JSX.IntrinsicElements
    children: undefined | number | string
}
