// packages/eviljs-reactx/text.tsx
import {asArray, isString} from '@eviljs/std/type.js'
import {useI18n} from '@eviljs/react/i18n.js'
import {classes} from '@eviljs/web/classes.js'
import {createElement, Fragment, Children} from 'react'

export function Text(props: TextProps) {
    const {children, className, tag = 'p', ...otherProps} = props
    const {translate} = useI18n()

    if (! children || Children.count(children) === 0) {
        return null
    }

    return (
        <Fragment>
            {asArray(children).map((it, idx) =>
                createElement(tag, {
                    ...otherProps,
                    key: idx,
                    className: classes('text-cea2a3', className),
                    children: isString(it)
                        ? translate(it)
                        : it
                    ,
                })
            )}
        </Fragment>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface TextProps extends React.HTMLAttributes<HTMLParagraphElement> {
    children?: React.ReactNode
    tag?: keyof JSX.IntrinsicElements
}

// packages/@eviljs/solid/text.tsx
import type {I18nMessageArgs} from '@eviljs/std/i18n.js'
import {isString} from '@eviljs/std/type.js'
import type {Accessor, JSX} from 'solid-js'
import {Show, splitProps} from 'solid-js'
import {Dynamic} from 'solid-js/web'
import {classes} from './classes.js'
import {createI18nMessage} from './i18n.js'

export function Text(props: TextProps) {
    const [_, otherProps] = splitProps(props, ['args', 'children', 'tag'])

    const message = createI18nMessage(
        () => isString(props.children)
            ? props.children
            : undefined
        ,
        props.args,
    )

    return (
        <Show when={message()}>
            <Dynamic
                {...otherProps}
                component={props.tag ?? 'span'}
                class={classes('Text-6e34', props.class)}
                data-key={message() !== props.children
                    ? props.children
                    : undefined
                }
                children={message()}
            />
        </Show>
    )
}

// Types ///////////////////////////////////////////////////////////////////////

export interface TextProps extends JSX.HTMLAttributes<HTMLElement> {
    args?: undefined | I18nMessageArgs | Accessor<I18nMessageArgs>
    children: undefined | string
    tag?: undefined | keyof JSX.IntrinsicElements
}
