// packages/@eviljs/solid/i18n.ts
import {compute} from '@eviljs/std/compute.js'
import type {I18n, I18nMessages, I18nSpec, MsgValues} from '@eviljs/std/i18n.js'
import {createI18n as createStdI18n} from '@eviljs/std/i18n.js'
import type {Accessor, Setter} from 'solid-js'
import {createContext, createMemo, createSignal, useContext} from 'solid-js'

export const I18nContext = createContext<Accessor<I18nManager>>()

export function useI18n() {
    return useContext(I18nContext)
}

export function createI18n(spec: I18nSpec<string, string, string, string>) {
    const [locale, setLocale] = createSignal(spec.locale)
    const [fallbackLocale, setFallbackLocale] = createSignal(spec.fallbackLocale)
    const [messages, setMessages] = createSignal(spec.messages)

    const i18n = createMemo((): I18nManager => {
        const manager = createStdI18n({
            ...spec,
            locale: locale(),
            fallbackLocale: fallbackLocale(),
            messages: messages(),
        })

        return {
            symbol: manager.symbol,
            format: manager.format,
            t: manager.t,
            translate: manager.translate,
            get locale() {
                return locale()
            },
            set locale(value) {
                setLocale(value)
            },
            setLocale,
            get fallbackLocale() {
                return fallbackLocale()
            },
            set fallbackLocale(value) {
                setFallbackLocale(value)
            },
            setFallbackLocale,
            get messages() {
                return messages()
            },
            set messages(value) {
                setMessages(value)
            },
            setMessages,
        }
    }, [locale, fallbackLocale, messages])

    return i18n
}

export function createI18nMessage(
    getId: string | Accessor<string>,
    getArgs?: undefined | MsgValues | Accessor<MsgValues>,
): Accessor<string>
export function createI18nMessage(
    getId: undefined | string | Accessor<undefined | string>,
    getArgs?: undefined | MsgValues | Accessor<MsgValues>,
): Accessor<undefined | string>
export function createI18nMessage(
    getId: undefined | string | Accessor<undefined | string>,
    getArgs?: undefined | MsgValues | Accessor<MsgValues>,
): Accessor<undefined | string> {
    const i18n = useI18n()!

    const message = createMemo(() => {
        const id = compute(getId)
        const args = compute(getArgs)

        return id
            ? i18n().translate(id, args)
            : undefined
    })

    return message
}

// Types ///////////////////////////////////////////////////////////////////////

export type I18nState = I18n<string, string>

export interface I18nManager<L extends string = string, K extends string = string> extends
    Omit<I18n<L, K>, '__regexpCache__'>,
    I18nSetters<L, K>
{
}

export interface I18nSetters<L extends string = string, K extends string = string> {
    setLocale: Setter<L>
    setFallbackLocale: Setter<L>
    setMessages: Setter<I18nMessages<L, K>>
}

// packages/react/i18n.tsx
import {createI18n, I18n as StdI18n, I18nMessages} from '@eviljs/std/i18n.js'
import {createContext, useContext, useMemo, useState} from 'react'

export const I18nContext = createContext<I18n>(void undefined as any)

I18nContext.displayName = 'I18nContext'

/*
* EXAMPLE
*
* const spec = {locale, fallbackLocale, messages}
* const i18n = createI18n(spec)
* const Main = WithI18n(MyMain, i18n)
*
* render(<Main/>, document.body)
*/
export function WithI18n<P extends {}>(Child: React.ComponentType<P>, spec: I18n) {
    function I18nProviderProxy(props: P) {
        return withI18n(<Child {...props}/>, spec)
    }

    return I18nProviderProxy
}

/*
* EXAMPLE
*
* const spec = {locale, fallbackLocale, messages}
* const i18n = createI18n(spec)
*
* export function MyMain(props) {
*     return withI18n(<Children/>, i18n)
* }
*/
export function withI18n(children: React.ReactNode, spec: StdI18n) {
    const [locale, setLocale] = useState(spec.locale)
    const [fallbackLocale, setFallbackLocale] = useState(spec.fallbackLocale)
    const [messages, setMessages] = useState(spec.messages)

    const i18n = useMemo(() => {
        const self: I18n = {
            ...createI18n({
                locale: locale,
                fallbackLocale: fallbackLocale,
                messages: messages,
            }),
            get locale() {
                return locale
            },
            set locale(value) {
                setLocale(value)
            },
            setLocale,
            get fallbackLocale() {
                return fallbackLocale
            },
            set fallbackLocale(value) {
                setFallbackLocale(value)
            },
            setFallbackLocale,
            get messages() {
                return messages
            },
            set messages(value) {
                setMessages(value)
            },
            setMessages,
        }

        return self
    }, [locale, fallbackLocale, messages])

    return (
        <I18nContext.Provider value={i18n}>
            {children}
        </I18nContext.Provider>
    )
}

/*
* EXAMPLE
*
* const spec = {locale, fallbackLocale, messages}
* const i18n = createI18n(spec)
*
* export function MyMain(props) {
*     return (
*         <I18nProvider i18n={i18n}>
*             <MyApp/>
*         </I18nProvider>
*     )
* }
*/
export function I18nProvider(props: I18nProviderProps) {
    return withI18n(props.children, props.i18n)
}

export function useI18n<I extends I18n>() {
    return useContext(I18nContext) as I
}

export function useI18nMsg<I extends I18n, T extends {}>(compute: I18nMsgsComputer<I, T>, deps?: Array<unknown>) {
    const i18n = useI18n<I>()
    const {locale, fallbackLocale, messages} = i18n

    const i18nMsg = useMemo(() => {
        return {
            ...compute(i18n),
            $i18n: i18n,
        }
    }, [i18n, locale, fallbackLocale, messages, ...(deps ?? [])])

    return i18nMsg
}

// Types ///////////////////////////////////////////////////////////////////////

export interface I18nProviderProps {
    children: React.ReactNode
    i18n: I18n
}

export interface I18nMsgsComputer<I extends I18n, T extends {}> {
    (i18n: I): T
}

export interface I18n<L extends string = string, K extends string = string> extends StdI18n<L, K>, I18nSetters<L, K> {
}

export interface I18nSetters<L extends string = string, K extends string = string> {
    setLocale(value: L): void
    setFallbackLocale(value: L): void
    setMessages(value: I18nMessages<L, K>): void
}
